### PR TITLE
fix the issue of inflow and outflow not incre/decrement

### PR DESCRIPTION
**Pull request by chenj926**
fix the issue of inflow and outflow not incre/decrement
in periodicTransaction

### CODE REVIEW

**Comment by chenj926** [comment]
everything looks good

**Comment by XileChen** [comment]
Looks good

**Comment by ChiFongHuang** [comment]
very well

**Comment by DkhDana05** [comment]
nice!

**Comment by misturiii** [comment]
Great! Everythings on good track!

**Comment by chenz623** [comment]
ok!

**Pull request merged**
