### PR TITLE
View

### PR DESCRIPTION
**Pull request by chenj926**
update the financial report view to allow it listen to the change in state to update views
update the error of not update to new user if we log out and log in again with a new user, still have some issue in financial report

### CODE REVIEW

**Comment by chenj926** [comment]
i will merge and solve conflict after the 2 reviewer take a look into it

**Comment by chenz623** [comment]
I think it should be fine.

**Comment by ChiFongHuang** [comment]
the changes are all good

**Comment by XileChen** [comment]
Everything is good

**Pull request closed without merging**
